# Generated by Django 5.1.6 on 2025-02-26 10:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 321641), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 321110), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_tagline', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
                ('company_address', models.TextField()),
                ('company_contact', models.CharField(max_length=10)),
                ('company_logo', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('social_links', models.JSONField()),
                ('office_hours', models.CharField(max_length=50)),
                ('google_map_url', models.CharField(max_length=500)),
                ('established_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 320817), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 323549), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 325027), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 326320), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 322689), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField()),
                ('status', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 319895), editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 321945), editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('blog_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='api.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment', to='api.blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogusercomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 324180), editable=False)),
                ('news_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.newscategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscomment', to='api.news')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsusercomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 325648), editable=False)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 326687), editable=False)),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 26, 15, 45, 28, 323055), editable=False)),
                ('webinar_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar', to='api.webinarcategory')),
            ],
        ),
    ]
