# Generated by Django 5.1.6 on 2025-02-26 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_created_at_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 242787), editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 245180), editable=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 244794), editable=False),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 244116), editable=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 243790), editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 247300), editable=False),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 246945), editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 248120), editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 248523), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 249643), editable=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 249281), editable=False),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 246502), editable=False),
        ),
        migrations.AlterField(
            model_name='webinarcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 16, 55, 53, 246027), editable=False),
        ),
    ]
