# Generated by Django 5.1.6 on 2025-02-28 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_created_at_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 478113), editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 480564), editable=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 480122), editable=False),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 479530), editable=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 479169), editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 482957), editable=False),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 482524), editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 483838), editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 484256), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 485363), editable=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 484982), editable=False),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 482030), editable=False),
        ),
        migrations.AlterField(
            model_name='webinarcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 12, 51, 29, 481574), editable=False),
        ),
    ]
