# Generated by Django 5.1.6 on 2025-03-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 782599), editable=False),
        ),
        migrations.AlterField(
            model_name='clientcompany',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 783916), editable=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 783617), editable=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 784784), editable=False),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 784428), editable=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 785481), editable=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 785799), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 786456), editable=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 786161), editable=False),
        ),
    ]
