# Generated by Django 5.1.6 on 2025-03-11 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ClientCompany',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.RemoveField(
            model_name='news',
            name='news_category_id',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_category_id',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 1, 22, 38, 703241), editable=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 1, 22, 38, 703862), editable=False),
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsComment',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
