# Generated by Django 5.1.6 on 2025-03-19 16:08

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', validators=[homepage.models.validate_image_size])),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=201)),
                ('cta', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
