# Generated by Django 5.1.6 on 2025-04-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
