# Generated by Django 5.1.6 on 2025-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='title',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='body',
            new_name='subtext',
        ),
    ]
