# Generated by Django 5.1.6 on 2025-03-20 06:47

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_title_hero_headline_rename_body_hero_subtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partnercompanies/', validators=[homepage.models.validate_image_size])),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
