# Generated by Django 5.1.6 on 2025-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_hero_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
