# Generated by Django 5.1.6 on 2025-04-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercompany',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
