# Generated by Django 5.1.6 on 2025-04-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_event_image', to='events.event')),
            ],
        ),
    ]
