# Generated by Django 5.1.6 on 2025-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
