# Generated by Django 5.1.6 on 2025-03-03 06:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 45, 44, 798972), editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_cat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 3, 11, 45, 44, 799540), editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
                ('blog_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blogs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment', to='blogs.blog')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogusercomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
