# Generated by Django 5.1.6 on 2025-03-07 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_delete_image_blog_image_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 11, 57, 48, 951042), editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 11, 57, 48, 950481), editable=False),
        ),
    ]
