# Generated by Django 5.1.6 on 2025-04-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_alter_blog_created_at_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 14, 27, 29, 760650), editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 14, 27, 29, 760093), editable=False),
        ),
    ]
