# Generated by Django 5.1.6 on 2025-04-07 08:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0003_alter_dogs_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 23, 44, 191165), editable=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('company', models.CharField(default='', max_length=255)),
                ('age', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(default='', max_length=500)),
                ('status', models.IntegerField()),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 23, 44, 191779), editable=False)),
                ('breed', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_breed', to='adoption.breed')),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
                ('product_category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.category')),
            ],
        ),
    ]
