# Generated by Django 5.1.6 on 2025-03-11 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_brand_product_type_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 57, 5, 755300), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 57, 5, 755881), editable=False),
        ),
    ]
