# Generated by Django 5.1.6 on 2025-04-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_weight_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 14, 27, 29, 767697), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 14, 27, 29, 768135), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
