# Generated by Django 5.1.6 on 2025-04-17 06:56

import datetime
import django.db.models.deletion
import services.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 12, 26, 48, 583498), editable=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='services/', validators=[services.models.validate_image_size])),
                ('status', models.IntegerField()),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 4, 17, 12, 26, 48, 584000), editable=False)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL)),
                ('service_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cat', to='services.category')),
            ],
        ),
    ]
