# Generated by Django 5.1.6 on 2025-03-10 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_category_created_at_alter_category_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 16, 33, 282055), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 16, 33, 282490), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(),
        ),
    ]
