# Generated by Django 5.1.6 on 2025-03-10 10:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_category_created_at_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 59, 32, 780252), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 15, 59, 32, 780838), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cat', to='services.category'),
        ),
    ]
