# Generated by Django 5.1.6 on 2025-04-17 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_category_created_at_alter_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 13, 11, 20, 592229), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 13, 11, 20, 592778), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(),
        ),
    ]
