# Generated by Django 5.1.6 on 2025-03-10 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_content_service_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_category_id',
            new_name='service_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 15, 13, 141751), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 15, 13, 142218), editable=False),
        ),
    ]
