# Generated by Django 5.1.6 on 2025-03-10 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_service_category_id_service_service_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_category',
            new_name='service_category_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 17, 16, 753171), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 16, 17, 16, 753646), editable=False),
        ),
    ]
