# Generated by Django 5.1.6 on 2025-04-17 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_rename_content_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 11, 18, 43, 13635), editable=False),
        ),
    ]
