# Generated by Django 5.1.6 on 2025-04-01 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_house_no_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 23, 28, 13, 978293), editable=False),
        ),
    ]
