# Generated by Django 5.1.6 on 2025-04-02 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address_phone_alter_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 47, 10, 936353), editable=False),
        ),
    ]
