# Generated by Django 5.1.6 on 2025-03-07 11:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 7, 16, 33, 42, 791747), editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
