# Generated by Django 5.1.6 on 2025-03-10 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 11, 51, 16, 126192), editable=False),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='image',
            field=models.ImageField(upload_to='webinars/'),
        ),
    ]
