# Generated by Django 5.1.6 on 2025-03-10 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_alter_webinar_created_at_alter_webinar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 12, 39, 54, 475194), editable=False),
        ),
    ]
