# Generated by Django 5.1.6 on 2025-03-10 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_alter_webinar_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 14, 43, 31, 734614), editable=False),
        ),
    ]
