# Generated by Django 5.1.6 on 2025-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
