# Generated by Django 5.1.6 on 2025-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
