# Generated by Django 5.1.6 on 2025-03-24 16:46

import adoption.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=12)),
                ('disease', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('personality', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dogs/', validators=[adoption.models.validate_image_size])),
                ('looking_for', models.TextField()),
                ('weight', models.FloatField()),
                ('energy_level', models.CharField(max_length=10)),
                ('vaccinated_status', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_breed', to='adoption.breed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adoption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
