# Generated by Django 5.1.6 on 2025-03-19 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=12)),
                ('disease', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('personality', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('looking_for', models.TextField()),
                ('Weight', models.FloatField()),
                ('size', models.FloatField()),
                ('energy_level', models.CharField(max_length=10)),
                ('vaccinated_status', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adoption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
