# Generated by Django 5.1.6 on 2025-03-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='age_type',
        ),
    ]
