# Generated by Django 5.1.6 on 2025-04-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_dogs_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
