# Generated by Django 5.1.6 on 2025-03-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_remove_dogs_age_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogs',
            name='size',
        ),
    ]
