# Generated by Django 5.1.6 on 2025-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_alter_dogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
