# Generated by Django 5.1.6 on 2025-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_remove_dogs_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='vaccinated_status',
            field=models.CharField(max_length=30),
        ),
    ]
