# Generated by Django 5.1.6 on 2025-04-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_dogs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='dog_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
