# Generated by Django 5.1.6 on 2025-03-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_dogs_vaccinated_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogs',
            old_name='Weight',
            new_name='weight',
        ),
    ]
