# Generated by Django 5.1.6 on 2025-03-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_rename_weight_dogs_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_breed', to='adoption.breed'),
        ),
    ]
