# Generated by Django 5.1.6 on 2025-03-19 16:08

import adoption.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_alter_dogs_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='image',
            field=models.ImageField(upload_to='dogs/', validators=[adoption.models.validate_image_size]),
        ),
    ]
